### ISSUE TITLE
Can't compile it on Ubuntu 16.04

### ISSUE THREAD

**Issue by elwardipol1** [endJunction/settleDyn#1]
I'm not sure this is a real issue, but It's driving me crazy that I'm not able to compile this interesting piece of software. My system information:
- Ubuntu 16.04 LTS; bullet2.83; haskell-platform v2014.2.0.0.debian2 (ghc v7.10.3-7)
- The configuration step looks successful

But the last part in the building one [9th, Compiling Main] seems to fail:

```
[9 of 9] Compiling Main             ( src/settleDyn.hs, dist/build/settleDyn/settleDyn-tmp/Main.o )
Linking dist/build/settleDyn/settleDyn ...
dist/build/settleDyn/settleDyn-tmp/BulletFFI.o: In function `c5zv_info':
(.text+0x468): undefined reference to `plSetPosition'
dist/build/settleDyn/settleDyn-tmp/BulletFFI.o: In function `c5Ft_info':
(.text+0xd30): undefined reference to `plCreateDynamicsWorld'
dist/build/settleDyn/settleDyn-tmp/BulletFFI.o: In function `c5Hj_info':
(.text+0x1120): undefined reference to `plGetOpenGLMatrix'
dist/build/settleDyn/settleDyn-tmp/BulletFFI.o: In function `c5KQ_info':
(.text+0x17a8): undefined reference to `plGetPosition'
collect2: error: ld returned 1 exit status
cabal: Error: some packages failed to install:
settleDyn-0.3.0.3 failed during the building phase. The exception was:
ExitFailure 1
```

Hope you can help me a bit here? My guess is that my bullet installation is
missing something, but I can't figure out what it is; Any help would be appreciated!

**Comment by endJunction** [comment]
Not sure about the origin of the error---I'll look into this over the weekend---but while linking there is a missing symbol `plSetPosition` (and few more). This symbols were removed in the bullet-2.83 version (see a [report here](https://abi-laboratory.pro/tracker/compat_report/bullet/2.82/2.83/cd280/abi_compat_report.html), search for `plSetPosition`).  There must be a replacement for that function, but I'll need some time...

**Comment by elwardipol1** [comment]
Thanks for the super-quick and useful feedback!!
Indeed, falling back to version 2.82 of bullet solved the problem; I'm simulating the examples now :+1:

**Comment by elwardipol1** [comment]
Hi again, 
This is embarrassing but I don't seem to recognize the mesh format you are using (resulting .mesh files). Even though you are naming their facility "PovWriter.hs", they don't seem to be pov meshes [(POV-RAY)](http://povray.org/). Is there a chance that I could convert them to a more common format (say .stl)?

**Comment by endJunction** [comment]
If I remember correctly (you see, I touched it 6 years ago last time), the output was written to `.off` files which are the Geomview Object File Format. See a note at the end of the [overview page](http://www.naumov.de/settleDyn/index.html). These you can process one by one by loading in blender or what not.
The povray output seems to produce a [mesh2 format](http://www.povray.org/documentation/view/3.7.1/68/) as mention in [this]( https://github.com/endJunction/settleDyn/blob/master/src/PovWriter.hs#L44-L54) comments. But I don't remember how to process the `mesh2` meshes with povray further. I'd guess you need a scene setup and include the mesh2 file there.
